import { copyFile, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildPublicStyles } from './build_public_styles.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const manifest = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
const libraries = {
  jquery: ['dist', 'src'],
  'chart.js': ['dist/chart.umd.min.js', 'dist/chart.umd.min.js.map'],
  jodit: ['es2021/jodit.min.js', 'es2021/jodit.min.css'],
  bootstrap: ['dist', 'js', 'less'],
  bootstrap5: ['dist/js/bootstrap.bundle.min.js', 'dist/js/bootstrap.bundle.min.js.map'],
  moment: ['locale', 'moment.js', 'min/locales.js', 'min/locales.min.js', 'min/moment.min.js',
    'min/moment-with-locales.js', 'min/moment-with-locales.min.js',
    'min/moment.min.js.map', 'min/moment-with-locales.min.js.map']
};

// PGCV does not use Button, Tooltip or Popover. Exclude these components
// affected by CVE-2024-6485 and CVE-2025-1647 from the served runtime.
const bootstrapModules = [
  'transition', 'alert', 'carousel', 'collapse', 'dropdown', 'modal',
  'scrollspy', 'tab', 'affix'
];

async function copyTree(source, target) {
  await mkdir(target, { recursive: true });
  for (const entry of await readdir(source, { withFileTypes: true })) {
    const input = path.join(source, entry.name);
    const output = path.join(target, entry.name);
    if (entry.isDirectory()) await copyTree(input, output);
    else if (entry.isFile()) await copyFile(input, output);
  }
}

// Check all installed versions before replacing any served assets.
for (const name of Object.keys(libraries)) {
  const installed = JSON.parse(await readFile(path.join(root, 'node_modules', name, 'package.json'), 'utf8'));
  const expectedVersion = manifest.dependencies[name].replace(/^npm:[^@]+@/, '');
  if (installed.version !== expectedVersion) {
    throw new Error(`Unexpected ${name} version. Run npm ci --ignore-scripts first.`);
  }
}

// Compile and validate the public theme before replacing other served assets.
await buildPublicStyles();

for (const [name, assets] of Object.entries(libraries)) {
  const source = path.join(root, 'node_modules', name);
  const target = path.join(root, 'bower_components', name);
  await mkdir(target, { recursive: true });
  for (const asset of assets) {
    if (['dist', 'src', 'js', 'less', 'locale'].includes(asset)) await copyTree(path.join(source, asset), path.join(target, asset));
    else {
      await mkdir(path.dirname(path.join(target, asset)), { recursive: true });
      await copyFile(path.join(source, asset), path.join(target, asset));
    }
  }
  for (const filename of ['.bower.json', 'bower.json', 'package.json']) {
    const destination = path.join(target, filename);
    try {
      const metadata = JSON.parse(await readFile(destination, 'utf8'));
      metadata.version = manifest.dependencies[name];
      delete metadata._resolution;
      delete metadata._release;
      metadata.pgcvAssetSource = `npm:${name}@${manifest.dependencies[name]}`;
      await writeFile(destination, JSON.stringify(metadata, null, 2) + '\n');
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
  }
  // Preserve the upstream license for redistributed runtime files.
  for (const license of ['LICENSE', 'LICENSE.txt', 'LICENSE.md']) {
    try { await copyFile(path.join(source, license), path.join(target, license)); }
    catch (error) { if (error.code !== 'ENOENT') throw error; }
  }
  console.log(`${name} ${manifest.dependencies[name]}: runtime assets synchronized`);
}

const bootstrapSources = await Promise.all(bootstrapModules.map(name =>
  readFile(path.join(root, 'node_modules/bootstrap/js', `${name}.js`), 'utf8')));
await mkdir(path.join(root, 'dist/js'), { recursive: true });
await writeFile(path.join(root, 'dist/js/bootstrap-pgcv.js'),
  '/* PGCV Bootstrap 3.4.1 runtime: excludes Button, Tooltip and Popover.\n' +
  ' * Generated by npm run sync:frontend. Upstream modules licensed under MIT. */\n' +
  bootstrapSources.join('\n;\n'));
console.log(`Bootstrap PGCV runtime generated: ${bootstrapModules.join(', ')}`);
